name: Team awesome's approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    name: Label when approved
    runs-on: ubuntu-latest
    steps:
      - uses: actions/label-when-approved-action@master
        with:
          name: Label when approved
          env:
            APPROVALS: 1
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ADD_LABEL: "Enough Approvers"
